"""empty message

Revision ID: 79983afd75a7
Revises: 21c5a27e51a9
Create Date: 2019-08-18 11:43:46.407982

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '79983afd75a7'
down_revision = '21c5a27e51a9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('check', sa.Column('message', sa.String(length=300), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('check', 'message')
    # ### end Alembic commands ###
